name: Deploy Tokenizer to Production

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: 22
          script: |
            cd /var/www/tokenizer.neiro-kod.ru
            git pull origin release
            npm ci
            npm run build
            sudo chown -R www-data:www-data dist
            sudo systemctl reload nginx
            echo "✅ Deployed!"
